## Fancy indexing

Indexing can be done with a list or an array of integers. In this case the same index can be also repeated several times:

In [1]:
import numpy as np
import matplotlib.pylab as plt

In [2]:
a = np.arange(0, 100, 10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [3]:
a[[2, 3, 2, 4, 2]] 

array([20, 30, 20, 40, 20])

New values can be also assigned with this kind of indexing:

In [4]:
a[[9, 7]] = -100
a

array([   0,   10,   20,   30,   40,   50,   60, -100,   80, -100])

When a new array is created by indexing with an array of integers, the new array has the same shape than the array of integers. 

In [5]:
a = np.arange(10)
idx = np.array([[3, 4], [9, 7]])
print('idx shape: {}'.format(idx.shape))
a[idx]

idx shape: (2, 2)


array([[3, 4],
       [9, 7]])

Fancy indexing is often used to re-order or sort data. You can easily obtain the indices required to sort data using np.argsort:

In [6]:
a = np.random.randint(10, size=5)
a

array([9, 9, 6, 0, 1])

In [7]:
i = np.argsort(a)
a[i]

array([0, 1, 6, 9, 9])

Note that fancy indexing returns a copy and not a view.

[Previous: Savez() and load()](savez.ipynb)<br>[Next: Stacking](stacking.ipynb) 