## Operations

Arrays also know how to perform common mathematical operations on their values. The simplest operations with data are arithmetic: addition, subtraction, multiplication, and division. When you do such operations on arrays, the operation is done element-by-element. <br>

In [32]:
import numpy as np

In [33]:
data = np.loadtxt(fname='../data/inflammation-01.csv', delimiter=',')

In [34]:
doubledata = data + data
print(doubledata)

[[0. 0. 2. ... 6. 0. 0.]
 [0. 2. 4. ... 2. 0. 2.]
 [0. 2. 2. ... 4. 2. 2.]
 ...
 [0. 2. 2. ... 2. 2. 2.]
 [0. 0. 0. ... 0. 4. 0.]
 [0. 0. 2. ... 2. 2. 0.]]


Operations by scalar:

In [35]:
tripledata = data * 3
print(tripledata)

[[0. 0. 3. ... 9. 0. 0.]
 [0. 3. 6. ... 3. 0. 3.]
 [0. 3. 3. ... 6. 3. 3.]
 ...
 [0. 3. 3. ... 3. 3. 3.]
 [0. 0. 0. ... 0. 6. 0.]
 [0. 0. 3. ... 3. 3. 0.]]


One of the advantages of NumPy is that it allows to apply functions (called ufuncs) to all elements of an array without the need of `for` loops:

In [36]:
np.sin(data[0,:])

array([ 0.        ,  0.        ,  0.84147098,  0.14112001,  0.84147098,
        0.90929743, -0.7568025 ,  0.6569866 ,  0.98935825,  0.14112001,
        0.14112001,  0.14112001, -0.54402111, -0.95892427,  0.6569866 ,
       -0.7568025 ,  0.6569866 ,  0.6569866 , -0.53657292, -0.75098725,
       -0.2794155 ,  0.42016704, -0.99999021, -0.99999021,  0.6569866 ,
        0.6569866 , -0.7568025 , -0.2794155 ,  0.98935825,  0.98935825,
       -0.7568025 , -0.7568025 , -0.95892427,  0.6569866 ,  0.14112001,
       -0.7568025 ,  0.90929743,  0.14112001,  0.        ,  0.        ])

This is not only convenient but also more efficient than iterating through the elements using for loops.

In [37]:
expdata = np.exp(data)
print(expdata)

[[ 1.          1.          2.71828183 ... 20.08553692  1.
   1.        ]
 [ 1.          2.71828183  7.3890561  ...  2.71828183  1.
   2.71828183]
 [ 1.          2.71828183  2.71828183 ...  7.3890561   2.71828183
   2.71828183]
 ...
 [ 1.          2.71828183  2.71828183 ...  2.71828183  2.71828183
   2.71828183]
 [ 1.          1.          1.         ...  1.          7.3890561
   1.        ]
 [ 1.          1.          2.71828183 ...  2.71828183  2.71828183
   1.        ]]


**Warning** Standard Python installation also includes the `math` library, but it does not play nicely with NumPy array and it may give different results than numpy function, so avoid using it with NumPy arrays.

Some functions (such as mean, max, etc.) aggregate the data return arrays of less dimensions or scalars:

In [38]:
sumdata = np.sum(data)
print('sum data: {}'.format(sumdata))

sum data: 14757.0


In [39]:
meandata = np.mean(data)
print(meandata)

6.14875


It's also possbile to average over a single axis:

In [40]:
np.mean(data, 0)

array([ 0.        ,  0.45      ,  1.11666667,  1.75      ,  2.43333333,
        3.15      ,  3.8       ,  3.88333333,  5.23333333,  5.51666667,
        5.95      ,  5.9       ,  8.35      ,  7.73333333,  8.36666667,
        9.5       ,  9.58333333, 10.63333333, 11.56666667, 12.35      ,
       13.25      , 11.96666667, 11.03333333, 10.16666667, 10.        ,
        8.66666667,  9.15      ,  7.25      ,  7.33333333,  6.58333333,
        6.06666667,  5.95      ,  5.11666667,  3.6       ,  3.3       ,
        3.56666667,  2.48333333,  1.5       ,  1.13333333,  0.56666667])

## Axis
<img src="../images/axis.png" alt="drawing" width=200 >

## $\color{green}{\text{Excercise}}$

Create array `a` with random elements of shape 1000 x 3.
Select the second and third column (index 1 and 2) and calculate the mean for each of the columns (i.e. your answer should be an array with two elements)

## $\color{green}{\text{Excercise}}$

Generate a 10 x 3 array of random numbers (using np.random.rand). From each row, find the column index of the element closest to 0.75. Make use of np.abs and np.argmin. The result should be a one-dimensional array of integers from 0 to 2.

## $\color{green}{\text{Excercise}}$ operations

Average the inflammation data over the first ten patients (rows) and plot them across time (columns). Then repeat it for the next ten patients and so on. Try putting all averages on a single plot

[Previous: Slices](slices.ipynb)<br>[Next: Stacking](stacking.ipynb) 