## Boolean mask

Sometimes we may want to select array elements based on their values. For this case boolean mask is very useful. The mask is an array of the same length as the indexed array containg only False or True values:

In [1]:
import numpy as np

In [2]:
a = np.arange(4)
print(a)

[0 1 2 3]


In [3]:
mask = np.array([False, True, True, False])
a[mask]

array([1, 2])

In most cases the mask is constructed from the values of the array itself. For example, to select only odd numbers we could use the following mask:

In [4]:
odd = (a % 2) == 1
odd

array([False,  True, False,  True])

In [5]:
np.array([False,  True, False,  True], dtype=bool)
a[odd]

array([1, 3])

This could be also done in a single step:

In [6]:
a[(a % 2) == 1]

array([1, 3])

## $\color{green}{\text{Quiz}}$  view or copy
What are the final values of a and b at the end of the following program? Explain why.

`a = np.arange(5)
b = a[a < 3]
b[::2] = 0`


a)  a = [0, 1, 2, 3, 4], b = [0, 1, 2] <br>
b)  a = [0, 1, 0, 3, 4], b = [0, 1, 0] <br>
c)  a = [0, 0, 2, 3, 4], b = [0, 0, 2] <br>
d)  a = [0, 1, 2, 3, 4], b = [0, 1, 0] <br>
e)  a = [0, 1, 2, 3, 4], b = [0, 1, 0, 3, 0] <br>

[Previous: Operations](operations.ipynb)<br>[Next: Stacking](stacking.ipynb)