## Filtering data
It's also possible to select elements (filter) based on a condition. 

In [1]:
import numpy as np
data = np.loadtxt(fname='../data/inflammation-01.csv', delimiter=',')

Sometimes we may want to select array elements based on their values. For this case boolean mask is very useful. The mask is an array of the same length as the indexed array containg only False or True values:

In [2]:
a = np.arange(4)
print(a)

[0 1 2 3]


In [3]:
mask = np.array([False, True, True, False])

In [4]:
a[mask]

array([1, 2])

In most cases the mask is constructed from the values of the array itself. For example, to select only odd numbers we could use the following mask:

In [5]:
odd = (a % 2) == 1
odd

array([False,  True, False,  True], dtype=bool)

In [6]:
np.array([False,  True, False,  True], dtype=bool)
a[odd]

array([1, 3])

This could be also done in a single step:

In [7]:
a[(a % 2) == 1]

array([1, 3])

## $\color{green}{\text{Excercise}}$ Filtering data
In the `data` what do you have to do to select all measurments above 10 in the first patient (index 0)?

In [8]:
patient0_data = data[0, :]
patient0_data[patient0_data > 10]

array([ 12.,  18.,  13.,  11.,  11.])

We can also substitute the measurement with a new value:

In [9]:
patient1_data = data[1, :]
patient1_data[patient1_data >1 0] = 10
print(patient1_data)

[  0.   1.   2.   1.   2.   1.   3.   2.   2.   6.  10.  10.   5.   9.   4.
   4.   7.  10.   8.   6.  10.   4.  10.   5.  10.   7.  10.   5.  10.   3.
   3.   5.   4.   4.   5.   5.   1.   1.   0.   1.]


[Previous: Working with a dataset](dataset_intro.ipynb)<br>[Next: Slices](slices.ipynb)