## $\color{green}{\text{Excercise}}$ Rectification

Rectify an array (replace negative elements with zeros) of random numbers from normal distribution (generated with np.random.randn) using boolean indexing.

## $\color{green}{\text{Excercise}}$ Sub-arrays

Let 
`x = np.array([1, 5, 10])`.

Which of the following will show `[1, 10]`:

a)    x[::2]

b)    x[[1, 3]]

c)    x[[0, 2]]

d)    x[0, 2]

e)    x[[1, -1]]

f)    x[[False, True, False]]

For each statement predict whether it returns a copy or a view.

## $\color{green}{\text{Excercise}}$ Random elements

Using fancy indexing select randomly with repetition 10 elements from a random array of 100 elements (Hint: you can use np.random.randint(max_int, size=n) to generate n random numbers from 0 to max_int)

## $\color{green}{\text{Excercise}}$ Drawing random integers without repetition

Generate a random sequence of 10 integers from 1 to 100 without repetition (Hint: you may want to use np.random.rand and np.argsort).

[Previous: Broadcasting](broadcasting.ipynb)<br>[Back to index](../01-numpy-introduction.ipynb)

## $\color{green}{\text{Excercise}}$

Generate a 10 x 3 array of random numbers (using np.random.rand). From each row, find the column index of the element closest to 0.75. Make use of np.abs and np.argmin. The result should be a one-dimensional array of integers from 0 to 2.

In [2]:
import numpy as np

rand_array = np.random.rand(10,3)
rand_array2 = rand_array - 0.75
closest = np.argmin(np.abs(rand_array2),1)
print(rand_array)
print(closest)

[[0.13654376 0.20663964 0.6687041 ]
 [0.79634026 0.74834001 0.78080021]
 [0.45507562 0.95150251 0.00874244]
 [0.56033834 0.8086642  0.57250754]
 [0.63135384 0.31754556 0.96671298]
 [0.20240249 0.65967628 0.6998376 ]
 [0.20280387 0.68140525 0.77317936]
 [0.47428802 0.48481599 0.72519364]
 [0.60341887 0.28140846 0.34091239]
 [0.50414201 0.40521352 0.28323068]]
[2 1 1 1 0 2 2 2 0 0]
